</br>

## STAVROS TSENTEMEIDIS    
Thessaloniki, Greece    
09/05/1996    
(+30) 6978418403   
s.tsentemeidis@student.ie.edu | stavros.tsentemeidis@gmail.com                

</br> 

<div style= "float:right;position: relative; top: -130px; right: -110px;">
<form method="get" action="Stavros_Tsentemeidis_CV_IE.pdf">
   <button type="submit" style="background-color:#272727"><span style="color:#0ce3ac">Download CV!</span></button>
</form>
</div>

<style>
p.main {
  text-align: justify;
}
</style>

### <span style="color:#0ce3ac">PROFESSIONAL SUMMARY</span>


<p class="main">My passion for analytics and the intense desire for <span style="color:#0ce3ac">extracting insights</span> out of data, led me to pursue a Master’s Degree in Business Analytics & Big Data. My <span style="color:#0ce3ac">will for excellence</span> ranked me 1st in my university entry exams. I have been <span style="color:#0ce3ac">leading</span> the Business Development department of an education startup called, Bonding Beyond Borders. I have also led a successful Racing Marketing Team, that achieved a great performance (2nd overall) at the FSAE International competition. I really love <span style="color:#0ce3ac">puzzles</span> and I want to expand this love to the business problems and learn how to solve them effectively through the <span style="color:#0ce3ac">power of Data & Analytics</span>.</p>

</br> 





### <span style="color:#0ce3ac">EDUCATION</span>  

###### <span style="color:#0ce3ac">➤ &nbsp;&nbsp;&nbsp; IE BUSINESS SCHOOL &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MADRID, SPAIN &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OCT. 2018 – JULY.2019</span>                 
*Master’s in Business Analytics & Big Data (MBD)*      
<p class="main">Knowledge acquired through the Master includes <span style="color:#0ce3ac">R, Python, Spark, Hadoop and SQL.</span>  There is also practical experience through Datathons and Enterprise Challenges (e.g. IBM Watson Challenge) organized by the IE University (HST).</p>


</br> 

###### <span style="color:#0ce3ac">➤ &nbsp;&nbsp;&nbsp;UNIVERSITY OF MACEDONIA &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; THESSALONIKI, GREECE &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SEPT. 2014 – JULY 2018</span>

Bachelor of Science, Business Administration                         				     	                       
<p class="main">1st ranking in the entry scores among the students during the academic year 2014 – 2015.</p>                                                   
</br> 









### <span style="color:#0ce3ac">PROFESSIONAL EXPERIENCE</span>    


###### <span style="color:#0ce3ac">➤ &nbsp;&nbsp;&nbsp;BONDING BEYOND BORDERS &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MADRID, SPAIN &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; FEB. 2019 – NOW</span>

*Business Development Director*     	                             
<p class="main">• Bonding Beyond Borders is a <span style="color:#0ce3ac">startup</span> on the <span style="color:#0ce3ac">educational sector</span>, focusing on helping the new generation broadening their horizon on the topic of <span style="color:#0ce3ac">diversity.</span> This is accomplished by assisting teachers discuss controversial <span style="color:#0ce3ac">social topics</span> (religion, immigrants, terrorism) with their students, in an interactive, fun and more comfortable way through our <span style="color:#0ce3ac">board game.</span></p>        
<p class="main">• Won the <span style="color:#0ce3ac">Global Facebook Challenge</span> last year and ended up 4th the following year <span style="color:#0ce3ac">among 50 teams</span>.</p>         
<p class="main">• Leading the <span style="color:#0ce3ac">business development</span> department of the company.</p>        
<p class="main">• Responsible for the <span style="color:#0ce3ac">expansion</span> of the business activities, as well as the development of <span style="color:#0ce3ac">pitches and presentations</span> for the different stakeholders, in order to bring them on board with our activities.</p>     

</br> 

###### <span style="color:#0ce3ac">➤ &nbsp;&nbsp;&nbsp; BLISS POINT PREMIUM FOOD PRODUCTS (ORIZONTES S.A) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; THESSALONIKI, GREECE &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SEP. 2017 – OCT.2018</span>

*Assistant Brand Manager*     	                             
<p class="main">• Developed part of the <span style="color:#0ce3ac">Point of Sale</span> material design and implementation.</p>      
<p class="main">• Responsible for the artwork implementation and the <span style="color:#0ce3ac">managing</span> of the social media communication.</p>     
<p class="main">• <span style="color:#0ce3ac">Participated</span> in Instore Consumer Testing events.</p>      

</br> 

###### <span style="color:#0ce3ac">➤ &nbsp;&nbsp;&nbsp; DEMOCRITUS RACING TEAM (N.G.O) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XANTHE, GREECE &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OCT.2015 – SEPT.2017</span>

*Marketing Manager*                                    
<p class="main">• <span style="color:#0ce3ac">Responsible</span> for the recruiting and managing of the team for 2 consecutive years, defining the roles and responsibilities.</p>  
<p class="main">• <span style="color:#0ce3ac">Leaded</span> the design and implementation of the <span style="color:#0ce3ac">Business Plan</span> at the team’s participation in the FSAE <span style="color:#0ce3ac">International Competition</span> (2nd place overall among 14 teams).</p>      


</br> 

###### <span style="color:#0ce3ac">➤ &nbsp;&nbsp;&nbsp; AHOLD DELHAIZE – ALFA BETA VASSILOPOULOS S.A &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; THESSALONIKI, GREECE &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; JUL. 2016 – OCT. 2016</span>
  
*Retail Corridor Assistant*                             		     				                                                 
<p class="main">• Specialized at the liquor/soft drinks corridor.</p>        
<p class="main">• Responsible for organizing the stock, filling empty shelves and making suggestions for the improvement of the recently renovated store.</p>  

</br> 

###### <span style="color:#0ce3ac">➤ &nbsp;&nbsp;&nbsp; PLAISIO COMPUTERS A.E.B.E &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; THESSALONIKI, GREECE &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; JUN.2015</span>
    
*Trainee*                                                                                                               
<p class="main">• I participated in the whole educational procedure of the company (3x 8hr seminars) to work as a smartphone salesman.</p>      
<p class="main">• Worked as an actual salesman as part of my education.</p>      

</br> 






### <span style="color:#0ce3ac">LANGUAGES</span> 

• &nbsp;&nbsp;&nbsp; <span style="color:red">English</span> (Bilingual)      
• &nbsp;&nbsp;&nbsp; <span style="color:#f6b511">Spanish</span> (Fluent, daily use since 2018)   
• &nbsp;&nbsp;&nbsp; <span style="color:#83ceec">Greek</span> (Native)    

</br>    








### <span style="color:#0ce3ac">OTHER INTERESTING INFORMATION</span>         
•	Great passion for Gaming (League of Legends, Counter Strike).     
•	Volunteer for AIESEC (2014).         
•	Volunteer for the Greek Red Cross – First Aid Courses for citizens (2016).         
<p class="main">• Google Certifications on Academy for Ads (Google <span style="color:#0ce3ac">Analytics</span> Individual Certification, AdWords <span style="color:#0ce3ac">Display</span> Certification, AdWords <span style="color:#0ce3ac">Search</span> Certification, AdWords <span style="color:#0ce3ac">Shopping</span> Certification, AdWords <span style="color:#0ce3ac">Video</span> Certification, <span style="color:#0ce3ac">Digital Sales</span> Certification, <span style="color:#0ce3ac">Mobile Sites</span> Certification, AdWords <span style="color:#0ce3ac">Fundamentals</span>, AdWords <span style="color:#0ce3ac">Mobile</span> Certification) (2018, 2019).</p>   

